# <-- JOINT PARAMETERS -->
max_torque: 6.5

#Homing positions
left_shoulder_hp: -0.0502
right_shoulder_hp: 0.0502
front_legs_hp: -0.55 #Limits are -2.66 alll the way to the back and 1.54 all the way to the front
rear_legs_hp: -0.5
front_feet_hp: 1.1
rear_feet_hp: 1

homing_pitch: -0.065 #Tilt body slightly forward for stability

#Mobility parameters: gains, deadzones, power
shoulder_gain: 0.9
shoulder_deadzone: 0.07
shoulder_power: 2

leg_gain: 0.8
leg_deadzone: 0.075
leg_power: 2.2

foot_gain: 0.65
foot_deadzone: 0.075
foot_power: 2.3

max_joint_velocity: 10 #Rad/s
max_norm_height: 0.235
max_linear_velocity: 2.23
max_forward_linear_velocity: 2.0
max_lateral_linear_velocity: 1.0
max_angular_velocity: 10

# <--  OTHER STUFF -->
joint_history_maxlen: 5
controller_type: "random"