# <-- ENVIRONMENT PARAMETERS -->
target_body_to_feet_height: 0.2
spawn_height: 0.230

#Target states
min_height: 0.15
max_height: 0.4
max_pitchroll: 0.96 #Radians = 55 degrees

#Termination rewards/penalties
survival_reward: 3.0
jump_fall_penalty: -100
tipping_penalty: -2

#Curricular shaping of terrain evolution
evolution_mode: "constant" #constant or exponential
c_potholes: 0.0
c_ridges: 0.25
c_roughness: 0.2