# <-- ENVIRONMENT PARAMETERS -->
target_body_to_feet_height: 0.2 # Previous 0.227
spawn_height: 0.230

#Target states: If the agents is in this state, we terminate the simulation.
min_height: 0.15
max_height: 0.4
max_pitchroll: 0.96 #Radians = 55 degrees

#Termination rewards/penalties
survival_reward: 3.0
jump_fall_penalty: -50
tipping_penalty: -2
