# <-- JOINT PARAMETERS -->
max_torque: 6.5

#Homing positions
left_shoulder_hp: -0.05
right_shoulder_hp: 0.05
front_legs_hp: -0.37
rear_legs_hp: -0.47
front_feet_hp: 1.15
rear_feet_hp: 1.08

homing_pitch: -0.07 #Tilt body slightly forward for stability

#Mobility parameters: gains, deadzones, power
shoulder_gain: 0.9
shoulder_deadzone: 0.07
shoulder_power: 2

leg_gain: 0.8
leg_deadzone: 0.075
leg_power: 2.2

foot_gain: 0.65
foot_deadzone: 0.075
foot_power: 2.3

# <--  OTHER STUFF -->
joint_history_maxlen: 5
spawn_height: 0.235
