mode: "irregular"

#Tilting plane parameters
rotation_frequency: 0.04
tilt_angle: 0.1745 #= 10 degrees

#Terraforming parameters
n_pits: 60
pit_radius: 0.10
pit_depth : 0.03

min_height_bumps: -0.05
max_height_bumps: 0.05
smooth_sigma_cells: 1.5
ridges_height: 0.025
ridges_distance: 0.35

cell_size: 0.05
grid_size: 256