# <-- ENVIRONMENT PARAMETERS -->
target_body_to_feet_height: 0.2
spawn_height: 0.230

#Target states
min_height: 0.15
max_height: 0.4
max_pitchroll: 0.96 #Radians = 55 degrees

#Normalization parameters
max_joint_velocity: 10 #Rad/s
max_norm_height: 0.235
max_linear_velocity: 2.0
max_angular_velocity: 10

#Termination rewards/penalties
survival_reward: 3.0
jump_fall_penalty: -100
tipping_penalty: -2
